version: '3.8'

services:
  green:
    image: 010709min/backend
    container_name: green
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - PROFILES=green
      - ENV=green
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - studiox-network

networks:
  studiox-network:
    external: true