version: '3.8'

services:
  blue:
    image: 010709min/backend
    container_name: blue
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PROFILES=blue
      - ENV=blue
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
        - studiox-network

networks:
  studiox-network:
    external: true
