version: "3.8"

services:
  prometheus:
    build:
      context: .
      dockerfile: config/prometheus/Dockerfile.prometheus
    image: studiox-prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    user: "${PROM_UID}:${PROM_GID}"
    expose:
      - "9090"
    volumes:
      - ./prometheus-data:/prometheus
    networks:
      - studiox-monitoring-network


  loki:
    build:
      context: .
      dockerfile: config/loki/Dockerfile.loki
    image: studiox-loki:2.9.8
    user: "0:0"
    container_name: loki
    ports:
      - "3100:3100"
    command: ["-config.expand-env=true", "-config.file=/etc/loki/custom.yaml"]
    volumes:
      - ./data/loki/data:/loki
    environment:
      TZ: "Asia/Seoul"
    networks:
      - studiox-monitoring-network

  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    command:
      - "--config.expand-env=true"
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_ENABLE_GZIP: true

    depends_on:
        - loki
    networks:
      - studiox-monitoring-network

networks:
  studiox-monitoring-network:
    name: studiox-monitoring-network


volumes:
  grafana-data:

