global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend-blue"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "${BACKEND_HOST}:${BLUE_PORT}"

  - job_name: "backend-green"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "${BACKEND_HOST}:${GREEN_PORT}"

  - job_name: "nginx"
    static_configs:
      - targets:
          - "${BACKEND_HOST}:${NGINX_PORT}"
